# Generated by Django 4.2.16 on 2024-11-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='wines', to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='whiskies', to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='NonAlcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='nonalcohols', to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=50)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('adult', models.BooleanField()),
                ('star_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('poster_url', models.TextField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.moviegenre')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='beers', to='movies.beverage')),
            ],
        ),
    ]
